name: CI Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21.1

      - name: Check npm Version
        run: node -v          

      - name: Check npm Version
        run: npm -v

      - name: Install ESLint
        run: npm install eslint --save-dev

      - name: Check ESLint Version
        run: npx eslint -v        