name: CI Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ESLINT_REPORT_PATH: '.\.github\workflows\eslint-report.json'
      ESLINT_MAX_WARNINGS: 2

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Check nodejs Version
        run: pwd       

      - name: Check npm Version
        run: npm -v

      - name: Install ESLint
        run: npm install eslint --save-dev

      - name: Check ESLint Version
        run: npx eslint -v        

      - name: Run ESLint and Generate Quality Report
        run: npx eslint . --format=json --output-file=$ESLINT_REPORT_PATH

      - name: Check Code Quality
        run: node check-quality.js --config .github/workflows/.eslintrc.js  $ESLINT_REPORT_PATH $ESLINT_MAX_WARNINGS