name: CI Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ESLINT_REPORT_PATH: './.github/workflows/eslint-report.json'
      ESLINT_MAX_WARNINGS: 2

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Check nodejs Version
        run: |
          node -v          
          pwd
          ls -la
          cat ./.github/workflows/.eslintrc.js

      - name: Check npm Version
        run: npm -v

      - name: Install ESLint
        run: npm install eslint --save-dev

      - name: Check ESLint Version
        run: npx eslint -v        

      - name: Run ESLint and Generate Quality Report
        id: eslint-step
        run: npx eslint . --config ./.github/workflows/.eslintrc.js --format=json --output-file=$ESLINT_REPORT_PATH
        continue-on-error: true

      - name: Show ESLint Report
        run: cat $ESLINT_REPORT_PATH

      - name: Check Quality
        run: |
          eslint_exit_code=${{ steps.eslint-exit-code.outputs.eslint_exit_code }}
          if [ $eslint_exit_code -ne 0 ]; then
            echo "ESLint found issues with a code of $eslint_exit_code."
            echo "Exiting the workflow with an error status."
            exit 1
          else
            echo "ESLint found no issues. Continuing with the workflow."
          fi

      #- name: Check Code Quality
      #  run: node check-quality.js $ESLINT_REPORT_PATH $ESLINT_MAX_WARNINGS